[package]
name = "fieldwise_derive"
version = "0.0.0"
authors = ["Hailey Somerville <hailey@hailey.lol>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
fieldwise = { path = ".." }
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
